### ISSUE TITLE
[FEAT]: Roadmap of Features/Changes

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/cookiecutter-python#1]
Documentation:
- [ ] add sphinx/mkdocs setup & poe command to initiate it
    - [ ] add custom mkdocs.yml project setup using cookiecutter variables
- [ ] Clarify and update micromamba installation process

Dependencies:
- [ ] replace `cz_gitmoji` with `czg/cz-git` and use in place of commitizen
- [ ] replace `typer` with `dtyper`
